name: zprime_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - xrootd
  - openssl>=3.5
  - jax
  - jaxlib
  - numpy
  - scipy
  - pandas
  - matplotlib
  - uproot
  - vector
  - coffea
  - tensorflow
  - scikit-learn
  - pip
  - pip:
      - wadler-lindig
      - tensorflow-metal
      - tensorflow-io-gcs-filesystem
      - stack-data
      - relaxed
      - pydantic-core
      - pyasn1-modules
      - notebook-shim
      - mypy-extensions
      - msgpack
      - mplhep-data
      - jupyter-events
      - jupyter-console
      - func-adl-servicex
      - fsspec-xrootd
      - fastjsonschema
      - docdantic
      - awkward-cpp
