[workspace]
channels = ["conda-forge"]
name = "z-prime-ttbar-gradients"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
# v2.8.6 is the last release to have JAX backend support
awkward = "==2.8.2"
cabinetry = ">=0.6.0,<0.7"
cloudpickle = ">=3.1.1,<4"
coffea = ">=2024,<2025"
correctionlib = ">=2.7.0,<3"
dask-awkward = ">=2025.5.0,<2026"
equinox = ">=0.13.0,<0.14"
evermore = ">=0.3.2,<0.4"
hist = ">=2.8.1,<3"
jax = ">=0.5.2,<0.6"
jaxopt = ">=0.8.4,<0.9"
jaxtyping = ">=0.3.2,<0.4"
mplhep = ">=0.4.0,<0.5"
numba = ">=0.61.2,<0.62"
numpy = ">=2.2.6,<3"
omegaconf = ">=2.3.0,<3"
optax = ">=0.2.4,<0.3"
pandas = ">=2.3.1,<3"
pydantic = ">=2.11.7,<3"
scikit-learn = ">=1.7.1,<2"
scipy = ">=1.16.0,<2"
tabulate = ">=0.9.0,<0.10"
tensorflow = ">=2.18.0,<3"
tqdm = ">=4.67.1,<5"
vector = "==1.5.1" # ">=1.6.3,<2"
python = ">=3.12.11,<3.13"
xrootd = ">=5.8.1,<6"

[pypi-dependencies]
relaxed = "==0.4.0"

[feature.lab.dependencies]
notebook = ">=7.4.5,<8"
jupyterlab = ">=4.4.5,<5"

[feature.lab.tasks.lab]
description = "Start a JupyterLab instance"
cmd = "jupyter lab"

[feature.lab.tasks.start]
description = "Get started with the repository"
depends-on = ["lab"]

[environments]
lab = ["lab"]
